package dbfork

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"google.golang.org/protobuf/encoding/prototext"
	"google.golang.org/protobuf/proto"

	"github.com/tronprotocol/tron-deployment/internal/dbfork/db"
	"github.com/tronprotocol/tron-deployment/internal/dbfork/stores"
	"github.com/tronprotocol/tron-deployment/internal/fsclone"
	pb "github.com/tronprotocol/tron-deployment/internal/tronproto/pb"
)

// equivalenceEnv is the set of environment variables that gate the
// real Go-vs-Java equivalence run. All three must be set (and resolve
// to existing files) for TestEquivalence_GoVsJava to actually run;
// otherwise the test SKIPs with a clear message so a developer
// without the Java toolkit / Nile fixture can still run `go test ./...`
// without failures.
//
//	DBFORK_NILE_FIXTURE  — path to the unzipped Nile snapshot
//	                       (the parent of `database/`). Generated by
//	                       scripts/build-nile-fixture.sh.
//	DBFORK_JAVA_TOOLKIT  — path to the toolkit.jar that contains the
//	                       java DbFork class. Build via:
//	                       cd tron-docker/tools/toolkit && ./gradlew shadowJar
//	DBFORK_FORK_CONF     — path to the fork.conf to apply. The
//	                       canonical reference is
//	                       tron-docker/tools/toolkit/src/main/resources/fork.conf
//	                       (HOCON). Both tools must see identical
//	                       bytes; the test reads it from this path
//	                       for the Go side and passes it to Java
//	                       unchanged.
const (
	envFixture = "DBFORK_NILE_FIXTURE"
	envJavaJar = "DBFORK_JAVA_TOOLKIT"
	envForkCnf = "DBFORK_FORK_CONF"
)

// TestEquivalence_GoVsJava is the Phase 1 release gate: it proves the
// Go port produces the same on-disk state as java DbFork when both
// are applied to the same Nile snapshot with the same fork.conf.
//
// The test SKIPs unless all three env vars (see equivalenceEnv) are
// set. This makes the local-dev `go test ./...` flow fast (no Nile
// download, no Java toolkit dependency) while still letting CI gate
// releases on the real equivalence proof.
//
// What it does when fully wired:
//
//  1. Copies the Nile fixture to two scratch tempdirs.
//  2. Loads fork.conf via the Go loader; runs MutateApply against
//     copy A.
//  3. Invokes `java -jar <toolkit.jar> db fork -d <copy B> -c <conf>`
//     against copy B.
//  4. For each of the 8 dbfork stores, iterates all key-value pairs
//     in both copies and diffs:
//     - Raw-byte compare for fixed-shape stores (properties,
//     witness_schedule, account-asset, storage-row).
//     - Proto-aware compare for variable-shape stores (witness,
//     account, contract, asset-issue-v2) — handles proto3 map
//     field non-deterministic encoding.
//  5. Fails on any diff at a key the fork.conf mutation writes (or
//     anywhere in the small fully-strict stores); logs diffs on
//     untouched pre-existing keys as the #168 read-layer artifact
//     without failing. Reports the first N diffs per store so a
//     failing run is debuggable without t.Fatal'ing on the very
//     first mismatch.
func TestEquivalence_GoVsJava(t *testing.T) {
	fixturePath, ok := mustEnvFile(t, envFixture, "Nile fixture", true)
	if !ok {
		return
	}
	javaJar, ok := mustEnvFile(t, envJavaJar, "java toolkit jar", false)
	if !ok {
		return
	}
	forkConfPath, ok := mustEnvFile(t, envForkCnf, "fork.conf", false)
	if !ok {
		return
	}
	if _, err := exec.LookPath("java"); err != nil {
		t.Skipf("equivalence: java binary not on PATH (set up JDK to run "+
			"the equivalence gate): %v", err)
		return
	}

	// Lay down two independent scratch copies — but ONLY of the 8
	// dbfork stores, not the whole snapshot. A full Nile snapshot is
	// ~90 GB and the giant non-dbfork stores (block, trans,
	// pbft-sign-data, …) blew the GitHub runner's disk when copied
	// twice ("no space left on device"). Both tools touch exactly
	// these 8 stores: Go's Apply opens them on demand and diffStore
	// iterates stores.AllStores; java DbFork's initStore() opens the
	// identical 8 (DbFork.java:120-127) and nothing else. So copying
	// only AllStores is provably sufficient AND cuts each scratch copy
	// from ~90 GB to a few GB.
	// Scratch dirs live ADJACENT to the fixture (same filesystem), NOT
	// under t.TempDir(). t.TempDir() resolves under os.TempDir()
	// (/var/folders, /tmp), which is frequently a different filesystem
	// than the cached fixture — and a copy-on-write clone across
	// filesystems fails with EXDEV and silently degrades to a full byte
	// copy. Co-locating scratch with the fixture is what lets
	// fsclone.CloneDir actually reflink; otherwise the optimization fires
	// nowhere (Task #185 review, Codex finding #4).
	fixtureParent := filepath.Dir(fixturePath)
	scratchRoot, err := os.MkdirTemp(fixtureParent, "dbfork-scratch-*")
	if err != nil {
		t.Fatalf("equivalence: create scratch root adjacent to fixture: %v", err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(scratchRoot) })
	scratchGo := filepath.Join(scratchRoot, "go")
	scratchJava := filepath.Join(scratchRoot, "java")
	t.Logf("equivalence: scratchGo=%s scratchJava=%s", scratchGo, scratchJava)
	for _, dst := range []string{scratchGo, scratchJava} {
		for _, store := range stores.AllStores {
			src := filepath.Join(fixturePath, "database", store)
			if _, statErr := os.Stat(src); statErr != nil {
				// A lite snapshot may legitimately prune a store (e.g.
				// storage-row); skip absent ones rather than fail. The
				// per-store diff will then show 0 keys on both sides.
				t.Logf("equivalence: store %q absent in fixture, skipping copy: %v", store, statErr)
				continue
			}
			method, cloneErr := fsclone.CloneDir(src, filepath.Join(dst, "database", store))
			if cloneErr != nil {
				t.Fatalf("equivalence: materialise store %q to %s: %v", store, dst, cloneErr)
			}
			t.Logf("equivalence: %s/%s materialised via %s", filepath.Base(dst), store, method)
		}
	}

	// Apply via Go.
	cfg, err := LoadConfig(forkConfPath)
	if err != nil {
		t.Fatalf("equivalence: load fork.conf: %v", err)
	}
	if _, err := Apply(scratchGo, cfg, Options{}); err != nil {
		t.Fatalf("equivalence: Go Apply: %v", err)
	}

	// Apply via Java DbFork. Output goes to t.Log so a failure has
	// the toolkit's own diagnostic in the test log.
	//
	// --retain-witnesses gating: Java's DbFork.java:160-167 wipes
	// witness + witness_schedule UNCONDITIONALLY when -r is absent,
	// regardless of whether fork.conf has a witnesses section. Go's
	// Apply (apply.go:155) only enters the witness branch when
	// len(cfg.Witnesses) > 0 — a deliberate UX safety call from
	// Task #147 to prevent properties-only fork.confs from
	// silently wiping witnesses. To bridge the divergence here,
	// we mirror Go's gating onto the Java invocation: if the conf
	// lists no witnesses, pass -r so Java also skips the wipe.
	javaArgs := []string{
		// -Xmx4g — Nile lite snapshots are multi-GB; the JDK
		// default heap (~256MB) OOMs the toolkit's account+contract
		// store readers. Configurable via DBFORK_JAVA_HEAP env var.
		javaHeapFlag(),
		"-jar", javaJar, "db", "fork",
		// -d is the output-directory (the PARENT of database/), NOT the
		// database/ dir itself: java DbFork's DbTool.getDB appends
		// `database/<store>` internally (DbFork.java:120 -> DbTool). The
		// Go side mirrors this — Apply(scratchGo) opens
		// scratchGo/database/<store>. Passing scratchJava/database here
		// made java look in scratchJava/database/database/<store> and
		// fail to open the LOCK. (Latent until the gate stopped
		// vacuously skipping — the java path was never exercised.)
		"-d", scratchJava,
		"-c", forkConfPath,
	}
	if len(cfg.Witnesses) == 0 {
		javaArgs = append(javaArgs, "--retain-witnesses")
	}
	javaCmd := exec.Command("java", javaArgs...)
	// Set the working directory to scratchJava so the toolkit's
	// logback writes to scratchJava/logs/ instead of polluting the
	// test runner's CWD.
	javaCmd.Dir = scratchJava
	javaOut, javaErr := javaCmd.CombinedOutput()
	if javaErr != nil {
		t.Fatalf("equivalence: java DbFork: %v\noutput:\n%s", javaErr, javaOut)
	}
	t.Logf("equivalence: java DbFork output:\n%s", javaOut)

	// Diff each of the 8 dbfork stores. Order is deterministic
	// (stores.AllStores) so a failing run always reports the same
	// store first, making CI bisection easier.
	//
	// Strictness is SCOPED, not per-store (#168). The big data stores
	// (account, account-asset, contract, asset-issue-v2, storage-row)
	// carry pre-existing DELETE tombstones + multi-version keys from
	// normal java-tron operation; the test reads BOTH outputs via
	// goleveldb, but java DbFork writes via leveldbjni, and the two
	// LevelDB implementations resolve such a physical layout differently
	// — so whole-store byte equality on those stores depends on the
	// compaction state of whatever Nile snapshot the weekly fixture
	// cache captured. It first bit account-asset/contract, then a later
	// snapshot tripped storage-row; ANY churn-heavy store can flip.
	// Confirmed on a real Nile snapshot (EC2 forensics): goleveldb and
	// leveldbjni return the IDENTICAL newest value for every multi-
	// version key, and leveldbjni reading the goleveldb-compacted ("Go
	// output") store returns the same newest values as reading java's
	// output — a shadow-fork booted from either output serves byte-
	// identical query results.
	//
	// So the gate's strict guarantee is exactly what dbfork promises:
	// every key the fork.conf mutation TOUCHES is byte-identical across
	// Go and Java (computed below by replaying the mutators against
	// recording spies — 100% production key-derivation, no duplication),
	// while diffs on untouched pre-existing keys are logged as the known
	// read-layer artifact without blocking. The three small mutation-
	// central stores (witness, witness_schedule, properties) stay fully
	// strict: they're rewritten wholesale by the fork (wipe semantics
	// included), tiny, and have never shown the artifact.
	targets := computeMutationTargets(t, scratchGo, cfg)
	fullStrict := map[string]bool{
		stores.WitnessStore:           true,
		stores.WitnessScheduleStore:   true,
		stores.DynamicPropertiesStore: true,
	}
	for _, store := range stores.AllStores {
		t.Run(store, func(t *testing.T) {
			diffStore(t, store, scratchGo, scratchJava, fullStrict[store], targets[store])
		})
	}
}

// computeMutationTargets replays the account + TRC20 mutators against
// recording spy engines to learn the exact key set the fork.conf
// mutation writes in the big data stores. Reads delegate to the (post-
// Apply) Go scratch stores; writes are recorded and DISCARDED, so the
// replay cannot perturb the state being diffed.
//
// Replaying against the already-mutated Go scratch is sound for KEY
// derivation: account keys are the decoded spec addresses; account-
// asset keys depend only on Account.AssetOptimized (which Apply never
// changes); storage-row keys depend only on the contract proto
// (contract store is read-only to dbfork). Values read may differ from
// the original run — only the recorded keys are used.
//
// A derivation bug in the engine cannot hide itself here: the test-
// derived key equals whatever (possibly wrong) key Go actually wrote,
// and the strict per-key compare then fails because java wrote the
// correct key instead — surfacing as a mutation-target key present
// only on the Go side.
func computeMutationTargets(t *testing.T, goRoot string, cfg *Config) map[string]map[string]bool {
	t.Helper()
	targets := map[string]map[string]bool{}

	if len(cfg.Accounts) > 0 {
		accountEng, err := db.OpenLevelDB(goRoot, stores.AccountStore)
		if err != nil {
			t.Fatalf("targets: open account: %v", err)
		}
		assetEng, err := db.OpenLevelDB(goRoot, stores.AssetIssueV2Store)
		if err != nil {
			t.Fatalf("targets: open asset-issue-v2: %v", err)
		}
		recAccount := &recordingEngine{inner: accountEng}
		recAccountAsset := &recordingEngine{}
		if _, err := MutateAccounts(recAccount, recAccountAsset, assetEng, cfg.Accounts); err != nil {
			t.Fatalf("targets: replay MutateAccounts: %v", err)
		}
		targets[stores.AccountStore] = recAccount.keys
		targets[stores.AccountAssetStore] = recAccountAsset.keys
		if err := accountEng.Close(); err != nil {
			t.Fatalf("targets: close account: %v", err)
		}
		if err := assetEng.Close(); err != nil {
			t.Fatalf("targets: close asset-issue-v2: %v", err)
		}
	}

	if len(cfg.TRC20Contracts) > 0 {
		contractEng, err := db.OpenLevelDB(goRoot, stores.ContractStore)
		if err != nil {
			t.Fatalf("targets: open contract: %v", err)
		}
		recStorageRow := &recordingEngine{}
		if _, err := MutateTRC20Contracts(contractEng, recStorageRow, cfg.TRC20Contracts); err != nil {
			t.Fatalf("targets: replay MutateTRC20Contracts: %v", err)
		}
		targets[stores.StorageRowStore] = recStorageRow.keys
		if err := contractEng.Close(); err != nil {
			t.Fatalf("targets: close contract: %v", err)
		}
	}

	for store, keys := range targets {
		t.Logf("targets: %s: %d fork.conf mutation-target keys", store, len(keys))
	}
	return targets
}

// recordingEngine is a db.Engine spy: Get/NewIterator delegate to the
// wrapped engine (nil inner is fine for write-only stores — the
// mutators never read those), while batches record write KEYS and drop
// the writes. Used by computeMutationTargets to learn the fork.conf
// mutation footprint from the production mutators themselves.
type recordingEngine struct {
	inner db.Engine
	keys  map[string]bool // hex-encoded keys of recorded Put/Delete calls
}

func (r *recordingEngine) Get(key []byte) ([]byte, error) { return r.inner.Get(key) }
func (r *recordingEngine) NewIterator() db.Iterator       { return r.inner.NewIterator() }
func (r *recordingEngine) Close() error                   { return nil } // caller owns inner
func (r *recordingEngine) NewBatch() db.Batch {
	if r.keys == nil {
		r.keys = map[string]bool{}
	}
	return &recordingBatch{keys: r.keys}
}

type recordingBatch struct{ keys map[string]bool }

func (b *recordingBatch) Put(key, _ []byte) { b.keys[hex.EncodeToString(key)] = true }
func (b *recordingBatch) Delete(key []byte) { b.keys[hex.EncodeToString(key)] = true }
func (b *recordingBatch) Write() error      { return nil }
func (b *recordingBatch) Close()            {}

// javaHeapFlag returns the JVM `-Xmx<size>` flag for the equivalence
// invocation. Defaults to `-Xmx4g` which is enough for Nile lite
// snapshots; CI on smaller runners can override via DBFORK_JAVA_HEAP
// (e.g. `2g`, `512m`). Without an override, the JDK default (~256MB)
// OOMs the toolkit's store readers on a real fixture.
func javaHeapFlag() string {
	heap := os.Getenv("DBFORK_JAVA_HEAP")
	if heap == "" {
		heap = "4g"
	}
	return "-Xmx" + heap
}

// mustEnvFile returns (path, true) when an env var is set AND the
// pointed file/dir exists with the expected kind. SKIPs with a
// descriptive message otherwise. Centralizes the gating logic so
// each missing prereq produces a uniform "go test ./..." log line.
//
// expectDir distinguishes the Nile-fixture case (must be a directory
// — the test later does `filepath.Join(path, "database")`) from the
// JAR + conf cases (must be a regular file). Without the kind check,
// pointing DBFORK_NILE_FIXTURE at a file would surface a confusing
// copyDir error rather than a clear "expected directory" message.
func mustEnvFile(t *testing.T, envName, label string, expectDir bool) (string, bool) {
	t.Helper()
	p := os.Getenv(envName)
	if p == "" {
		t.Skipf("equivalence: %s ($%s) not set — see equivalence_test.go "+
			"docstring for setup. Skipping the Go-vs-Java release gate.",
			label, envName)
		return "", false
	}
	info, err := os.Stat(p)
	if err != nil {
		t.Skipf("equivalence: %s at %q ($%s) not accessible: %v — skipping.",
			label, p, envName, err)
		return "", false
	}
	if expectDir && !info.IsDir() {
		t.Skipf("equivalence: %s at %q ($%s) is a file, want a directory — skipping.",
			label, p, envName)
		return "", false
	}
	if !expectDir && info.IsDir() {
		t.Skipf("equivalence: %s at %q ($%s) is a directory, want a file — skipping.",
			label, p, envName)
		return "", false
	}
	return p, true
}

// diffStore opens the same store in both scratch dirs and compares
// every key-value pair. Splits raw vs proto-aware paths based on
// the store's content type.
//
// Failure semantics are per-KEY (#168): a diff fails the test when the
// store is fullStrict (witness/witness_schedule/properties) or the key
// is in targets (a key the fork.conf mutation writes — computed by
// computeMutationTargets). Diffs on other keys are pre-existing-data
// noise from the goleveldb-vs-leveldbjni read-layer artifact and are
// logged with a #168 prefix without failing. Every target key must
// additionally be PRESENT on both sides — a mutator that silently
// dropped a write would otherwise diff clean (absent == absent).
func diffStore(t *testing.T, store, goRoot, javaRoot string, fullStrict bool, targets map[string]bool) {
	t.Helper()
	strictAt := func(hk string) bool { return fullStrict || targets[hk] }
	artifactf := func(format string, args ...any) {
		t.Logf("#168 KNOWN-ARTIFACT (non-blocking) "+format, args...)
	}

	goEng, err := db.OpenLevelDB(goRoot, store)
	if err != nil {
		t.Fatalf("open Go %s: %v", store, err)
	}
	defer goEng.Close()
	javaEng, err := db.OpenLevelDB(javaRoot, store)
	if err != nil {
		t.Fatalf("open Java %s: %v", store, err)
	}
	defer javaEng.Close()

	goMap, err := collectAllKV(goEng)
	if err != nil {
		t.Fatalf("collect Go %s: %v", store, err)
	}
	javaMap, err := collectAllKV(javaEng)
	if err != nil {
		t.Fatalf("collect Java %s: %v", store, err)
	}
	// Log per-store key counts so a vacuously-passing run (empty
	// store on both sides — possible if the lite snapshot pruned
	// `storage-row`, for example) is visible in the test log.
	t.Logf("%s: %d keys on Go, %d keys on Java", store, len(goMap), len(javaMap))

	// Mutation-target coverage: every key the mutators write must
	// exist on BOTH sides before any value comparison.
	for _, hk := range sortedKeySet(targets) {
		if _, ok := goMap[hk]; !ok {
			t.Errorf("%s: mutation-target key %s missing on Go side", store, hk)
		}
		if _, ok := javaMap[hk]; !ok {
			t.Errorf("%s: mutation-target key %s missing on Java side", store, hk)
		}
	}

	// Key-set diff next — surfaces extra/missing keys before drowning
	// the log in value diffs.
	reportKeySetDiff(store, "Go", keysOnlyIn(goMap, javaMap), strictAt, t.Errorf, artifactf)
	reportKeySetDiff(store, "Java", keysOnlyIn(javaMap, goMap), strictAt, t.Errorf, artifactf)

	// Per-key value compare. Cap reported diffs (strict and artifact
	// counted separately) so a wholesale regression doesn't write
	// thousands of lines.
	const maxValueDiffs = 5
	strictDiffs, softDiffs := 0, 0
	for _, hk := range sortedHexKeys(goMap) {
		jv, ok := javaMap[hk]
		if !ok {
			continue // already reported by reportKeySetDiff
		}
		gv := goMap[hk]
		equal, why := compareValue(store, gv, jv)
		if equal {
			continue
		}
		if strictAt(hk) {
			strictDiffs++
			if strictDiffs <= maxValueDiffs {
				t.Errorf("%s: key %s: %s", store, hk, why)
			}
		} else {
			softDiffs++
			if softDiffs <= maxValueDiffs {
				artifactf("%s: key %s: %s", store, hk, why)
			}
		}
	}
	if strictDiffs > maxValueDiffs {
		t.Errorf("%s: %d additional strict value diffs not shown (cap=%d)",
			store, strictDiffs-maxValueDiffs, maxValueDiffs)
	}
	if softDiffs > maxValueDiffs {
		artifactf("%s: %d additional value diffs not shown (cap=%d)",
			store, softDiffs-maxValueDiffs, maxValueDiffs)
	}
}

// compareValue picks proto-aware or raw compare based on the store's
// schema. Returns (equal, why) where why is non-empty on mismatch.
func compareValue(store string, goVal, javaVal []byte) (bool, string) {
	switch store {
	case stores.WitnessStore:
		return compareProto(goVal, javaVal, &pb.Witness{})
	case stores.AccountStore:
		return compareProto(goVal, javaVal, &pb.Account{})
	case stores.ContractStore:
		return compareProto(goVal, javaVal, &pb.SmartContract{})
	case stores.AssetIssueV2Store:
		// DbFork doesn't write this store, so any diff is unexpected.
		// Proto-compare for robustness against future expansion.
		return compareProto(goVal, javaVal, &pb.AssetIssueContract{})
	default:
		// Raw byte stores: witness_schedule (concat addresses),
		// properties (BE int64), account-asset (BE int64),
		// storage-row (32-byte balance).
		if bytes.Equal(goVal, javaVal) {
			return true, ""
		}
		return false, fmt.Sprintf("raw bytes differ:\n go=%s\n java=%s",
			hex.EncodeToString(goVal), hex.EncodeToString(javaVal))
	}
}

// compareProto parses both sides into a fresh proto of the given type
// and compares with proto.Equal (which is field-aware and tolerant of
// proto3 map field encoding-order differences — the same divergence
// that motivates accounts.go's deterministic-marshal). Returns a
// human-readable diff via prototext on mismatch.
//
// proto.Equal is ORDER-DEPENDENT for repeated fields (Account.votes,
// Account.frozen, etc.). DbFork doesn't mutate these — both java and
// Go round-trip the on-disk order untouched — so the order-dependence
// is invisible at the equivalence boundary. If a future mutator
// rewrites a repeated field, this comment is the place to revisit.
func compareProto(goVal, javaVal []byte, exemplar proto.Message) (bool, string) {
	goCopy := proto.Clone(exemplar)
	if err := proto.Unmarshal(goVal, goCopy); err != nil {
		return false, fmt.Sprintf("Go-side unmarshal failed: %v", err)
	}
	javaCopy := proto.Clone(exemplar)
	if err := proto.Unmarshal(javaVal, javaCopy); err != nil {
		return false, fmt.Sprintf("Java-side unmarshal failed: %v", err)
	}
	if proto.Equal(goCopy, javaCopy) {
		return true, ""
	}
	// Use prototext for human-readable diffs (skips byte-level
	// noise that proto.Equal already proved equivalent).
	goText, _ := prototext.MarshalOptions{Multiline: true}.Marshal(goCopy)
	javaText, _ := prototext.MarshalOptions{Multiline: true}.Marshal(javaCopy)
	return false, fmt.Sprintf("proto fields differ:\n--- go ---\n%s\n--- java ---\n%s",
		string(goText), string(javaText))
}

// collectAllKV iterates the entire store into an in-memory map. For
// equivalence diffing this is fine — even a 100M-row store at 100
// bytes per row is 10GB; mainstream Nile lite fixtures are much
// smaller. If a future fixture is too large, swap to a streaming
// merge-join over sorted iterators.
func collectAllKV(eng db.Engine) (map[string][]byte, error) {
	out := map[string][]byte{}
	it := eng.NewIterator()
	defer it.Close()
	for it.Next() {
		k := it.Key()
		v := it.Value()
		out[hex.EncodeToString(k)] = v
	}
	if err := it.Error(); err != nil {
		return nil, err
	}
	return out, nil
}

// reportKeySetDiff reports keys present on the named side only,
// partitioned by strictness: mutation-target (or fullStrict) keys go
// to strictf (t.Errorf at the diffStore call site — fails the gate);
// the rest go to artifactf as #168 noise. Both reporters are injected
// so the partition itself is unit-testable without failing the suite.
// Caps each partition so a wholesale regression doesn't flood the log.
func reportKeySetDiff(store, side string, only []string,
	strictAt func(string) bool, strictf, artifactf func(string, ...any)) {
	const maxKeyDiffs = 5

	var strictKeys, softKeys []string
	for _, k := range only {
		if strictAt(k) {
			strictKeys = append(strictKeys, k)
		} else {
			softKeys = append(softKeys, k)
		}
	}
	if len(strictKeys) > 0 {
		n := min(len(strictKeys), maxKeyDiffs)
		strictf("%s: %d strict keys present only on %s side; first %d: %v",
			store, len(strictKeys), side, n, strictKeys[:n])
	}
	if len(softKeys) > 0 {
		n := min(len(softKeys), maxKeyDiffs)
		artifactf("%s: %d keys present only on %s side; first %d: %v",
			store, len(softKeys), side, n, softKeys[:n])
	}
}

func keysOnlyIn(a, b map[string][]byte) []string {
	var out []string
	for k := range a {
		if _, present := b[k]; !present {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}

// sortedKeySet returns the keys of a string-set in sorted order, so
// target-coverage failures report deterministically across runs.
func sortedKeySet(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedHexKeys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// Fixture materialisation (CoW clone with byte-copy fallback) lives in
// internal/fsclone now — see fsclone.CloneDir, exercised above. The
// former test-local cloneDir/copyDir/copyFile were lifted there so there
// is a single clone+copy implementation (Task #185 review, DRY).

// --- Diff-helper unit tests ----------------------------------------------
//
// These exercise the per-store diff helpers without the Java toolkit
// or the Nile fixture, so the equivalence test's logic is itself
// pinned. A regression in compareValue/compareProto/keysOnlyIn would
// surface here even when the full release gate doesn't run.

func TestCompareValue_RawByteEqual(t *testing.T) {
	a := []byte{1, 2, 3}
	b := []byte{1, 2, 3}
	equal, why := compareValue(stores.DynamicPropertiesStore, a, b)
	if !equal {
		t.Errorf("expected equal, got why=%q", why)
	}
}

func TestCompareValue_RawByteDiffers(t *testing.T) {
	a := []byte{1, 2, 3}
	b := []byte{1, 2, 4}
	equal, why := compareValue(stores.StorageRowStore, a, b)
	if equal {
		t.Error("expected diff, got equal")
	}
	for _, want := range []string{"raw bytes differ", "010203", "010204"} {
		if !strings.Contains(why, want) {
			t.Errorf("diff message missing %q: %s", want, why)
		}
	}
}

// TestCompareValue_ProtoMapEqualUnderReordering pins the proto.Equal-
// based map handling. Two Account protos with the same AssetV2 entries
// in different insertion orders MUST compare equal — otherwise Java's
// non-deterministic marshalling vs Go's deterministic marshalling
// would falsely fail the equivalence gate.
//
// Construction note: we hand-build two wire-format byte sequences with
// the AssetV2 entries in EXPLICITLY reversed order, instead of relying
// on Go's map iteration ordering. Map iteration is randomized at
// runtime but the randomization seed is stable within a process, so a
// `proto.Marshal` of two map literals with the same entries can
// accidentally produce identical bytes — which would make this test
// pass even if compareValue did byte-equality. The hand-built bytes
// guarantee the precondition we care about (goBytes != javaBytes) and
// the test asserts it explicitly.
func TestCompareValue_ProtoMapEqualUnderReordering(t *testing.T) {
	addr := bytes.Repeat([]byte{0x41}, 21)

	// Build the wire format by composing each side from two
	// single-entry Accounts. proto3 map fields are encoded as a
	// repeated entry; two consecutive entries can appear in either
	// order on the wire and decode to the same map.
	mk := func(id string, bal int64) []byte {
		raw, _ := proto.Marshal(&pb.Account{
			Address: addr,
			AssetV2: map[string]int64{id: bal},
		})
		return raw
	}
	entryA := mk("1000001", 100)
	entryB := mk("1000002", 200)

	// Strip the address from entryB's bytes and append to entryA;
	// the proto3 wire format allows duplicate field encoding (later
	// values append for map/repeated). The result decodes to a
	// 2-entry map but the on-wire order differs by argument order.
	goBytes := append([]byte{}, entryA...)
	goBytes = append(goBytes, entryB...)
	javaBytes := append([]byte{}, entryB...)
	javaBytes = append(javaBytes, entryA...)

	if bytes.Equal(goBytes, javaBytes) {
		t.Fatal("test precondition: hand-built byte sequences must differ; " +
			"the proto.Equal robustness is not actually being exercised")
	}

	equal, why := compareValue(stores.AccountStore, goBytes, javaBytes)
	if !equal {
		t.Errorf("proto.Equal-based diff failed under map reordering: %s", why)
	}
}

func TestCompareValue_ProtoDifferentFieldFails(t *testing.T) {
	goWitness := &pb.Witness{
		Address:   bytes.Repeat([]byte{0x41}, 21),
		VoteCount: 100,
	}
	javaWitness := &pb.Witness{
		Address:   bytes.Repeat([]byte{0x41}, 21),
		VoteCount: 101, // deliberate diff
	}
	goBytes, _ := proto.Marshal(goWitness)
	javaBytes, _ := proto.Marshal(javaWitness)
	equal, why := compareValue(stores.WitnessStore, goBytes, javaBytes)
	if equal {
		t.Error("expected proto diff on different VoteCount")
	}
	if !strings.Contains(why, "proto fields differ") {
		t.Errorf("diff message should mention proto fields: %s", why)
	}
	// prototext uses the proto3 camelCase JSON name `voteCount`, not
	// the wire-format name `vote_count`. Both 100 and 101 should
	// appear in the diff so an operator can see the discrepancy.
	if !strings.Contains(why, "voteCount") {
		t.Errorf("diff message should mention voteCount, got: %s", why)
	}
	if !strings.Contains(why, "100") || !strings.Contains(why, "101") {
		t.Errorf("diff message should show both values, got: %s", why)
	}
}

// TestRecordingEngine_CapturesWriteKeys pins the spy used by
// computeMutationTargets: batch Put/Delete keys are recorded (hex)
// across multiple batches, writes are dropped, and Close never
// touches the wrapped engine.
func TestRecordingEngine_CapturesWriteKeys(t *testing.T) {
	rec := &recordingEngine{}
	b1 := rec.NewBatch()
	b1.Put([]byte{0x01, 0x02}, []byte("v"))
	b1.Delete([]byte{0x03})
	if err := b1.Write(); err != nil {
		t.Fatalf("recording Write: %v", err)
	}
	b1.Close()
	b2 := rec.NewBatch()
	b2.Put([]byte{0x04}, nil)
	if err := b2.Write(); err != nil {
		t.Fatalf("recording Write: %v", err)
	}
	b2.Close()

	want := []string{"0102", "03", "04"}
	if len(rec.keys) != len(want) {
		t.Fatalf("recorded %d keys (%v); want %d", len(rec.keys), rec.keys, len(want))
	}
	for _, k := range want {
		if !rec.keys[k] {
			t.Errorf("key %q not recorded; got %v", k, rec.keys)
		}
	}
	if err := rec.Close(); err != nil {
		t.Errorf("recordingEngine.Close: %v", err)
	}
}

// TestReportKeySetDiff_PartitionsByStrictness pins the #168 scoped-
// strictness split: a one-sided key routes to the strict reporter
// (t.Errorf at the real call site) only when strictAt says so; others
// go to the artifact logger.
func TestReportKeySetDiff_PartitionsByStrictness(t *testing.T) {
	var stricts, artifacts []string
	strictf := func(format string, args ...any) {
		stricts = append(stricts, fmt.Sprintf(format, args...))
	}
	artifactf := func(format string, args ...any) {
		artifacts = append(artifacts, fmt.Sprintf(format, args...))
	}
	strictAt := func(hk string) bool { return hk == "aa" }

	// Soft-only side: nothing strict, both keys logged as artifact.
	reportKeySetDiff("store-x", "Go", []string{"bb", "cc"}, strictAt, strictf, artifactf)
	if len(stricts) != 0 {
		t.Errorf("soft-only keys routed to strict reporter: %v", stricts)
	}
	if len(artifacts) != 1 || !strings.Contains(artifacts[0], "2 keys present only on Go side") {
		t.Errorf("soft keys not routed to artifact log: %v", artifacts)
	}

	// Mixed side: the target key is strict, the other stays artifact.
	reportKeySetDiff("store-x", "Java", []string{"aa", "bb"}, strictAt, strictf, artifactf)
	if len(stricts) != 1 || !strings.Contains(stricts[0], "1 strict keys present only on Java side") {
		t.Errorf("strict one-sided key not routed to strict reporter: %v", stricts)
	}
	if len(artifacts) != 2 || !strings.Contains(artifacts[1], "1 keys present only on Java side") {
		t.Errorf("soft key alongside strict not routed to artifact log: %v", artifacts)
	}
}

func TestKeysOnlyIn_ReturnsDifference(t *testing.T) {
	a := map[string][]byte{"k1": nil, "k2": nil, "k3": nil}
	b := map[string][]byte{"k2": nil}
	got := keysOnlyIn(a, b)
	want := []string{"k1", "k3"}
	if len(got) != len(want) {
		t.Fatalf("keysOnlyIn = %v; want %v", got, want)
	}
	for i, k := range want {
		if got[i] != k {
			t.Errorf("keysOnlyIn[%d] = %q; want %q", i, got[i], k)
		}
	}
}

// Round-trip + independence + forced-fallback coverage for the fixture
// clone now lives with the implementation in internal/fsclone
// (TestCloneDir_RoundTrip, TestCloneDir_ForcedFallback,
// TestRecursiveCopy_RoundTrip). Keeping the tests next to CloneDir means
// the seam that forces the byte-copy fallback can be exercised
// deterministically on any host — see Task #185.

// Note: the "skip cleanly when env vars missing" path is exercised
// by every `go test ./...` run on a machine without the Java toolkit
// or Nile fixture — TestEquivalence_GoVsJava itself reports SKIP
// under those conditions, which is visible in `go test -v` output
// and would surface as a test FAILURE (not skip) if a regression
// broke the gating. A separate "test the skip" test is unnecessary.
